### ISSUE TITLE
[firefox-kde][thunderbird-kde] Add patches to match non-kde version (font fixes)

### ISSUE THREAD

**Issue by VladimirSchowalter20** [manjaro/packages-community#370]
After upgrading `freetype2` to `2.8.1` fonts in `firefox-kde` and `thunderbird-kde` are blurred. This is already fixed in `firefox 55.0.3-3` and `thunderbird 52.3.0-2` (among other few patches). Please update kde specific versions.

Related bugreport from Arch: https://bugs.archlinux.org/task/55714

thunderbird changes:
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/thunderbird&id=5143375c7519e57b56a3ecc2d407e2cb59c790e3

firefox changes:
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/firefox&id=c39edac40da353a5676457260b9b7ced9f5362fc
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/firefox&id=44e8e010c7c02cbae56a2bbc1254ba43c22a3b85

**Comment by philmmanjaro** [comment]
Thx for pointing this out. I had the same issues with the normal packages until I synced them. @Kirek, when ever you find time for it.

**Comment by BS86** [comment]
Like already written in the thread: I replaced the two packages in question with their non-KDE counterparts and can not see any negative effects so far on my KDE machines. the font issue is fixed. 
Are those packages really still needed? Wouldn’t it be better to replace them with the “pure” firefox and thunderbird packages?

**Comment by philmmanjaro** [comment]
The packages are for friends wanting to have the KDE dialog, however not really needed. We have to discuss this. **GTK** is needed anyway ...

**Comment by Kirek** [comment]
Currently I have problems to rebuild firefox-kde with the new glibc, even without applying the kde patches. It fails around the end of the build process.
If anyone want to try, pushed the PKGBUILD here https://github.com/manjaro/packages-community/commit/099344c3c9cb7ec70a6b769b7069bf9f815e5640
At least thunderbird-kde compiled fine and I'm pushing it to unstable now.

**Comment by Ste74** [comment]
Try to build just now..

**Comment by VladimirSchowalter20** [comment]
@Kirek you forgot to add `glibc-2.26-fix.diff` to firefox-kde repo...

@philmmanjaro please don't remove them :smile:  It's main thing keeping me with manjaro.

**Comment by Kirek** [comment]
The glibc fix is the mozilla-ucontext patch.

**Comment by VladimirSchowalter20** [comment]
You can try to replace them as they're slightly different. As non-kde version builds successfully we have to cut all potential differencies.
https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/firefox

**Comment by philmmanjaro** [comment]
@Kirek: there is a difference:

```
-@@ -471,17 +471,17 @@ bool ExceptionHandler::HandleSignal(int 
+                        callback_context_)) {
+       return true;
+     }
+   }
+   return GenerateDump(&g_crash_context_);
+ }
+ 
```
so we should use the new patch for now.

**Comment by philmmanjaro** [comment]
Forget about the noise. Seems still to be valid. We have to check why it doesn't work and try to use the new patch anyway.

**Comment by philmmanjaro** [comment]
Lets see if my **Ryzen** machine with new microcode might compile it or not. Will keep you updated.

**Comment by Ste74** [comment]
Cross the fingers.. my intel i5 7200  fail...

**Comment by philmmanjaro** [comment]
Well, mine also:

```
161:53.92 make[3]: *** [/build/firefox-kde/src/firefox-55.0.3/config/recurse.mk:33: compile] Error 2
161:54.03 make[2]: *** [/build/firefox-kde/src/firefox-55.0.3/config/rules.mk:519: default] Error 2
161:54.17 make[1]: *** [/build/firefox-kde/src/firefox-55.0.3/client.mk:419: realbuild] Error 2
161:54.23 make: *** [client.mk:170: build] Error 2
161:54.39 306 compiler warnings present.
Error running mach:

    ['build']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

AssertionError

  File "/build/firefox-kde/src/firefox-55.0.3/python/mozbuild/mozbuild/mach_commands.py", line 528, in build
    monitor.finish(record_usage=status==0)
  File "/build/firefox-kde/src/firefox-55.0.3/python/mozbuild/mozbuild/mach_commands.py", line 241, in __exit__
    self.monitor.stop_resource_recording()
  File "/build/firefox-kde/src/firefox-55.0.3/python/mozbuild/mozbuild/controller/building.py", line 258, in stop_resource_recording
    self.resources.stop()
  File "/build/firefox-kde/src/firefox-55.0.3/testing/mozbase/mozsystemmonitor/mozsystemmonitor/resourcemonitor.py", line 289, in stop
    assert self._running
==> ERROR: A failure occurred in build().
    Aborting...
```
Considering it is not worth the compile time, I'd suggest to drop it. Thoughts?

**Comment by philmmanjaro** [comment]
I've [dropped firefox-kde](https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20170925/012808.html) for now. Until we can build it properly, I see no other option for it.

**Comment by Kirek** [comment]
Fine for me. We may think to drop thunderbird-kde too.

**Comment by philmmanjaro** [comment]
@Kirek: I'm also fine with that. Should we do that in this update-review-cycle? The benefit is few and the effort is huge. So for me it makes not so much sense to keep them.

**Comment by BS86** [comment]
Just to make it clear - the solution is that firefox* packages will replace firefox-kde* packages and the same for thunderbird? I think that it would be bad for users to be left without updates. Not many are reading release notes / the forum.

**Comment by philmmanjaro** [comment]
for sure the issue is with **freetype v2.8.1**. I've created now an older version based on **v2.8** and it is working with **firefox** and **thunderbird** packages aimed for **v2.8.1** just fine. Also **wine** has issues with the new **freetype** release. We will see.

**Comment by hawkeye116477** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1384062
Fix -> https://aur.archlinux.org/cgit/aur.git/tree/fixformach.diff?h=firefox-clean

**Comment by philmmanjaro** [comment]
@Kirek: I added now the patch to https://github.com/manjaro/packages-community/commit/acfb2f4c418c9eb2e05a205bf509dc737a6a6a4b. Maybe it compiles now.

**Comment by Kirek** [comment]
Ok, I will give it a try now.

**Comment by Kirek** [comment]
With that patch it finally compiles.

**Comment by torvic9** [comment]
Not really an issue since the section is commented, but `MOZ_PGO=1 ./mach build` doesn't work.
Just put `export MOZ_PGO=1` and leave `./mach build` as is.
The PGO build itself does work.

**Comment by VladimirSchowalter20** [comment]
Before I close this one:

https://github.com/manjaro/packages-community/commit/acfb2f4c418c9eb2e05a205bf509dc737a6a6a4b#diff-f17a00656c0d3af517cc9c21c96159ceR142
Is re-enabling this intentional?

**Comment by philmmanjaro** [comment]
**crashreporter** was never the issue ...

**Comment by VladimirSchowalter20** [comment]
I know it's unrelated but I noticed crashreporter was disabled with https://github.com/manjaro/packages-community/commit/c49a405dc456a970c758f56a8b7ea3084c18b917#diff-09f6da03ff7c886a7f9680276e028459 then re-enabled with commit posted above which fixed this very issue. Is this omission or intended?
